FROM python:3.12-slim

WORKDIR /app

COPY transpiler/requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY transpiler/transpiler_service.py /app/

EXPOSE 5002

CMD ["python", "transpiler_service.py"]
